"""updated_server_default_vals_in_Empresa

Revision ID: 023c09953e3c
Revises: 470a5cdcc1c8
Create Date: 2023-06-13 16:03:47.375723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023c09953e3c'
down_revision = '470a5cdcc1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.alter_column('conv_exames', server_default=sa.text('1'))
        batch_op.alter_column('conv_exames_corpo_email', server_default=sa.text('1'))
        batch_op.alter_column('conv_exames_convocar_clinico', server_default=sa.text('0'))
        batch_op.alter_column('conv_exames_nunca_realizados', server_default=sa.text('0'))
        batch_op.alter_column('conv_exames_per_nunca_realizados', server_default=sa.text('0'))
        batch_op.alter_column('conv_exames_pendentes', server_default=sa.text('0'))
        batch_op.alter_column('conv_exames_pendentes_pcmso', server_default=sa.text('0'))
        batch_op.alter_column('conv_exames_selecao', server_default=sa.text('1'))

        batch_op.alter_column('exames_realizados', server_default=sa.text('1'))

        batch_op.alter_column('absenteismo', server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.alter_column('conv_exames', server_default=None)
        batch_op.alter_column('conv_exames_corpo_email', server_default=None)
        batch_op.alter_column('conv_exames_convocar_clinico', server_default=None)
        batch_op.alter_column('conv_exames_nunca_realizados', server_default=None)
        batch_op.alter_column('conv_exames_per_nunca_realizados', server_default=None)
        batch_op.alter_column('conv_exames_pendentes', server_default=None)
        batch_op.alter_column('conv_exames_pendentes_pcmso', server_default=None)
        batch_op.alter_column('conv_exames_selecao', server_default=None)

        batch_op.alter_column('exames_realizados', server_default=None)

        batch_op.alter_column('absenteismo', server_default=None)
    # ### end Alembic commands ###
