"""added mandato configs

Revision ID: 41afdc28074b
Revises: 48dd5baf7d6c
Create Date: 2023-08-14 14:38:13.664505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41afdc28074b'
down_revision = '48dd5baf7d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MandatoConfigEmpresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('load_hist', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('monit_erros', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('monit_venc', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('emails', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_empresa')
    )
    op.create_table('MandatoConfigUnidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('monit_erros', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('monit_venc', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('emails', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_unidade')
    )
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('mandatos_cipa_emails')
        batch_op.drop_column('erros_mandt_cipa')
        batch_op.drop_column('hist_mandt_cipa')

    with op.batch_alter_table('Unidade', schema=None) as batch_op:
        batch_op.drop_column('mandatos_cipa_emails')
        batch_op.drop_column('erros_mandt_cipa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erros_mandt_cipa', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('mandatos_cipa_emails', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hist_mandt_cipa', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('erros_mandt_cipa', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('mandatos_cipa_emails', sa.VARCHAR(length=500), nullable=True))

    op.drop_table('MandatoConfigUnidade')
    op.drop_table('MandatoConfigEmpresa')
    # ### end Alembic commands ###
