"""added grupo_empresa_prestador_socnet

Revision ID: 470a5cdcc1c8
Revises: b7acf53bc71f
Create Date: 2023-06-01 18:19:47.155187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470a5cdcc1c8'
down_revision = 'b7acf53bc71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_empresa_prestador_socnet',
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_prestador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['EmpresaSOCNET.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo_empresa_prestador_socnet')
    # ### end Alembic commands ###
