"""added modelo rtc to Empresa

Revision ID: 48dd5baf7d6c
Revises: 5c98a3ea5429
Create Date: 2023-07-21 10:37:34.569998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dd5baf7d6c'
down_revision = '5c98a3ea5429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=100), server_default='grs.png', nullable=True))
        batch_op.add_column(sa.Column('modelo_rtc', sa.String(length=100), server_default='rtc_default.html', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('modelo_rtc')
        batch_op.drop_column('logo')
    # ### end Alembic commands ###
