"""added dominios_email to Empresa

Revision ID: 5c98a3ea5429
Revises: a28225176187
Create Date: 2023-07-10 16:54:03.526258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c98a3ea5429'
down_revision = 'a28225176187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dominios_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('central_avisos_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('dominios_email')
        batch_op.add_column(sa.Column('central_avisos_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
