"""updated Unidade

Revision ID: a28225176187
Revises: c646d7d99e94
Create Date: 2023-06-29 18:10:16.768200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28225176187'
down_revision = 'c646d7d99e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EmpresaPrincipal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chaves_exporta_dados', sa.String(length=255), nullable=True))

    with op.batch_alter_table('Unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_server_update', sa.DateTime(), nullable=True))
        batch_op.drop_column('razao_social')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('razao_social', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('last_server_update')

    with op.batch_alter_table('EmpresaPrincipal', schema=None) as batch_op:
        batch_op.drop_column('chaves_exporta_dados')

    # ### end Alembic commands ###
