"""added ped proc config

Revision ID: ada8a2fb87a1
Revises: 48dd5baf7d6c
Create Date: 2023-08-04 14:14:13.089688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada8a2fb87a1'
down_revision = '48dd5baf7d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PedProcConfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.Column('periodo_timedelta_dias', sa.Integer(), server_default=sa.text('731'), nullable=True),
    sa.Column('selecao', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('convocar_clinico', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('nunca_realizados', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('per_nunca_realizados', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('pendentes', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('pendentes_pcmso', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_empresa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PedProcConfig')
    # ### end Alembic commands ###
