"""Initial commit, database vazia

Revision ID: b7acf53bc71f
Revises: 
Create Date: 2023-05-23 18:20:21.854174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7acf53bc71f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmailConnect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_to', sa.String(length=500), nullable=False),
    sa.Column('email_cc', sa.String(length=500), nullable=True),
    sa.Column('email_bcc', sa.String(length=500), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('attachments', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('df_len', sa.Integer(), nullable=True),
    sa.Column('ped_proc', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('obs', sa.String(length=255), nullable=True),
    sa.Column('email_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EmpresaPrincipal',
    sa.Column('cod', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('socnet', sa.Boolean(), nullable=False),
    sa.Column('configs_exporta_dados', sa.String(length=255), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cod')
    )
    op.create_table('ExportaDadosWS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_method', sa.String(length=20), nullable=False),
    sa.Column('request_url', sa.String(length=255), nullable=False),
    sa.Column('request_body', sa.String(length=2000), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.String(length=2000), nullable=True),
    sa.Column('parametros', sa.String(length=2000), nullable=False),
    sa.Column('erro_soc', sa.Boolean(), nullable=False),
    sa.Column('msg_erro', sa.String(length=255), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('obs', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Grupo',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('nome_grupo', sa.String(length=255), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('LogAcoes',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('nome_registro', sa.String(length=255), nullable=True),
    sa.Column('obs', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('Login',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('tela', sa.String(length=50), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('obs', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('RTC',
    sa.Column('id_rtc', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome_rtc', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_rtc')
    )
    op.create_table('Status',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('nome_status', sa.String(length=100), nullable=False),
    sa.Column('finaliza_processo', sa.Boolean(), nullable=False),
    sa.Column('status_padrao', sa.Boolean(), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('StatusLiberacao',
    sa.Column('id_status_lib', sa.Integer(), nullable=False),
    sa.Column('nome_status_lib', sa.String(length=50), nullable=False),
    sa.Column('cor_tag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_status_lib')
    )
    op.create_table('StatusRAC',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('nome_status', sa.String(length=100), nullable=False),
    sa.Column('status_padrao', sa.Boolean(), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('TipoExame',
    sa.Column('cod_tipo_exame', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome_tipo_exame', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_exame')
    )
    op.create_table('TipoUsuario',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('Empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_empresa', sa.Integer(), nullable=False),
    sa.Column('nome_abrev', sa.String(length=255), nullable=True),
    sa.Column('razao_social_inicial', sa.String(length=255), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('emails', sa.String(length=500), nullable=True),
    sa.Column('cnpj', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=5), nullable=True),
    sa.Column('conv_exames', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_emails', sa.String(length=500), nullable=True),
    sa.Column('conv_exames_corpo_email', sa.Integer(), nullable=True),
    sa.Column('conv_exames_convocar_clinico', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_nunca_realizados', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_per_nunca_realizados', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_pendentes', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_pendentes_pcmso', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_selecao', sa.Integer(), nullable=True),
    sa.Column('exames_realizados', sa.Boolean(), nullable=True),
    sa.Column('exames_realizados_emails', sa.String(length=500), nullable=True),
    sa.Column('absenteismo', sa.Boolean(), nullable=True),
    sa.Column('absenteismo_emails', sa.String(length=500), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.Column('last_server_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('EmpresaSOCNET',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_referencia', sa.Integer(), nullable=False),
    sa.Column('cod_empresa', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=255), nullable=False),
    sa.Column('emails', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('Exame',
    sa.Column('id_exame', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_exame', sa.String(length=255), nullable=False),
    sa.Column('nome_exame', sa.String(length=255), nullable=False),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.PrimaryKeyConstraint('id_exame')
    )
    op.create_table('Prestador',
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_prestador', sa.Integer(), nullable=True),
    sa.Column('nome_prestador', sa.String(length=255), nullable=False),
    sa.Column('emails', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('solicitar_asos', sa.Boolean(), nullable=True),
    sa.Column('cnpj', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=4), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.PrimaryKeyConstraint('id_prestador')
    )
    op.create_table('RTCCargos',
    sa.Column('cod_cargo', sa.String(length=255), nullable=True),
    sa.Column('id_rtc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rtc'], ['RTC.id_rtc'], )
    )
    op.create_table('RTCExames',
    sa.Column('id_rtc', sa.Integer(), nullable=True),
    sa.Column('cod_tipo_exame', sa.Integer(), nullable=True),
    sa.Column('cod_exame', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cod_tipo_exame'], ['TipoExame.cod_tipo_exame'], ),
    sa.ForeignKeyConstraint(['id_rtc'], ['RTC.id_rtc'], )
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cookie', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nome_usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha', sa.String(length=300), nullable=False),
    sa.Column('otp', sa.String(length=300), nullable=True),
    sa.Column('chave_api', sa.String(length=300), nullable=True),
    sa.Column('tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tipo_usuario'], ['TipoUsuario.id_role'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_cookie'),
    sa.UniqueConstraint('username')
    )
    op.create_table('UsuarioSOC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=400), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cod_cargo', sa.String(length=255), nullable=False),
    sa.Column('nome_cargo', sa.String(length=300), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('cbo', sa.String(length=255), nullable=True),
    sa.Column('cod_rh', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.String(length=100), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('qtd_inseridos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('qtd_atualizados', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ok', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('erro', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PedidoProcessamento',
    sa.Column('id_proc', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_solicitacao', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cod_empresa', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('resultado_importado', sa.Boolean(), nullable=False),
    sa.Column('relatorio_enviado', sa.Boolean(), nullable=False),
    sa.Column('parametro', sa.String(length=500), nullable=False),
    sa.Column('obs', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_proc')
    )
    op.create_table('PedidoSOCNET',
    sa.Column('id_ficha', sa.Integer(), nullable=False),
    sa.Column('seq_ficha', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_referencia', sa.Integer(), nullable=False),
    sa.Column('cod_funcionario', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=True),
    sa.Column('nome_funcionario', sa.String(length=150), nullable=False),
    sa.Column('data_ficha', sa.Date(), nullable=False),
    sa.Column('cod_tipo_exame', sa.Integer(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('id_status_rac', sa.Integer(), nullable=False),
    sa.Column('data_recebido', sa.Date(), nullable=True),
    sa.Column('data_comparecimento', sa.Date(), nullable=True),
    sa.Column('obs', sa.String(length=255), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['cod_tipo_exame'], ['TipoExame.cod_tipo_exame'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['EmpresaSOCNET.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], ),
    sa.ForeignKeyConstraint(['id_status'], ['Status.id_status'], ),
    sa.ForeignKeyConstraint(['id_status_rac'], ['StatusRAC.id_status'], ),
    sa.PrimaryKeyConstraint('id_ficha')
    )
    op.create_table('Unidade',
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cod_unidade', sa.String(length=255), nullable=False),
    sa.Column('nome_unidade', sa.String(length=255), nullable=False),
    sa.Column('emails', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('cod_rh', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('conv_exames', sa.Boolean(), nullable=True),
    sa.Column('conv_exames_emails', sa.String(length=500), nullable=True),
    sa.Column('conv_exames_corpo_email', sa.Integer(), nullable=True),
    sa.Column('exames_realizados', sa.Boolean(), nullable=True),
    sa.Column('exames_realizados_emails', sa.String(length=500), nullable=True),
    sa.Column('absenteismo', sa.Boolean(), nullable=True),
    sa.Column('absenteismo_emails', sa.String(length=500), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_unidade')
    )
    op.create_table('grupo_empresa',
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], )
    )
    op.create_table('grupo_empresa_prestador',
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_prestador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], )
    )
    op.create_table('grupo_empresa_socnet',
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['EmpresaSOCNET.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], )
    )
    op.create_table('grupo_prestador',
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_prestador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], )
    )
    op.create_table('grupo_usuario',
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], )
    )
    op.create_table('ExamesRealizados',
    sa.Column('id_realizado', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('seq_ficha', sa.Integer(), nullable=False),
    sa.Column('cod_funcionario', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=True),
    sa.Column('nome_funcionario', sa.String(length=150), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('data_ficha', sa.Date(), nullable=False),
    sa.Column('data_resultado', sa.Date(), nullable=False),
    sa.Column('cod_tipo_exame', sa.Integer(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_exame', sa.Integer(), nullable=False),
    sa.Column('cod_setor', sa.String(length=255), nullable=True),
    sa.Column('nome_setor', sa.String(length=255), nullable=True),
    sa.Column('cod_cargo', sa.String(length=255), nullable=True),
    sa.Column('nome_cargo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['cod_tipo_exame'], ['TipoExame.cod_tipo_exame'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_exame'], ['Exame.id_exame'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_realizado')
    )
    op.create_table('Funcionario',
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('cod_funcionario', sa.Integer(), nullable=False),
    sa.Column('nome_funcionario', sa.String(length=100), nullable=True),
    sa.Column('cpf_funcionario', sa.String(length=20), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('cod_setor', sa.String(length=100), nullable=True),
    sa.Column('nome_setor', sa.String(length=100), nullable=True),
    sa.Column('cod_cargo', sa.String(length=100), nullable=True),
    sa.Column('nome_cargo', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('data_adm', sa.Date(), nullable=True),
    sa.Column('data_dem', sa.Date(), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_funcionario')
    )
    op.create_table('Pedido',
    sa.Column('id_ficha', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('seq_ficha', sa.Integer(), nullable=False),
    sa.Column('cod_funcionario', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=True),
    sa.Column('nome_funcionario', sa.String(length=150), nullable=True),
    sa.Column('data_ficha', sa.Date(), nullable=False),
    sa.Column('cod_tipo_exame', sa.Integer(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('id_status_rac', sa.Integer(), nullable=False),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('prev_liberacao', sa.Date(), nullable=True),
    sa.Column('id_status_lib', sa.Integer(), nullable=False),
    sa.Column('data_recebido', sa.Date(), nullable=True),
    sa.Column('data_comparecimento', sa.Date(), nullable=True),
    sa.Column('obs', sa.String(length=255), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.String(length=50), nullable=True),
    sa.Column('alterado_por', sa.String(length=50), nullable=True),
    sa.Column('last_server_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['cod_tipo_exame'], ['TipoExame.cod_tipo_exame'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], ),
    sa.ForeignKeyConstraint(['id_status'], ['Status.id_status'], ),
    sa.ForeignKeyConstraint(['id_status_lib'], ['StatusLiberacao.id_status_lib'], ),
    sa.ForeignKeyConstraint(['id_status_rac'], ['StatusRAC.id_status'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_ficha'),
    sa.UniqueConstraint('seq_ficha')
    )
    op.create_table('ConvExames',
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('id_proc', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_exame', sa.Integer(), nullable=False),
    sa.Column('periodicidade', sa.Integer(), nullable=True),
    sa.Column('data_adm', sa.Date(), nullable=True),
    sa.Column('ult_pedido', sa.Date(), nullable=True),
    sa.Column('data_res', sa.Date(), nullable=True),
    sa.Column('refazer', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_exame'], ['Exame.id_exame'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['Funcionario.id_funcionario'], ),
    sa.ForeignKeyConstraint(['id_proc'], ['PedidoProcessamento.id_proc'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_conv')
    )
    op.create_table('Licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('tipo_licenca', sa.String(length=255), nullable=True),
    sa.Column('cod_medico', sa.Integer(), nullable=True),
    sa.Column('nome_medico', sa.String(length=255), nullable=True),
    sa.Column('data_ficha', sa.Date(), nullable=False),
    sa.Column('data_inicio_licenca', sa.Date(), nullable=True),
    sa.Column('data_fim_licenca', sa.Date(), nullable=True),
    sa.Column('afast_horas', sa.Boolean(), nullable=True),
    sa.Column('hora_inicio_licenca', sa.Integer(), nullable=True),
    sa.Column('hora_fim_licenca', sa.Integer(), nullable=True),
    sa.Column('motivo_licenca', sa.String(length=255), nullable=True),
    sa.Column('cid_contestado', sa.String(length=255), nullable=True),
    sa.Column('cod_cid', sa.String(length=255), nullable=True),
    sa.Column('tipo_cid', sa.String(length=255), nullable=True),
    sa.Column('solicitante', sa.String(length=255), nullable=True),
    sa.Column('data_inclusao_licenca', sa.Date(), nullable=True),
    sa.Column('dias_afastado', sa.Integer(), nullable=True),
    sa.Column('periodo_afastado', sa.Integer(), nullable=True),
    sa.Column('abonado', sa.Boolean(), nullable=True),
    sa.Column('cid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['Funcionario.id_funcionario'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Licenca')
    op.drop_table('ConvExames')
    op.drop_table('Pedido')
    op.drop_table('Funcionario')
    op.drop_table('ExamesRealizados')
    op.drop_table('grupo_usuario')
    op.drop_table('grupo_prestador')
    op.drop_table('grupo_empresa_socnet')
    op.drop_table('grupo_empresa_prestador')
    op.drop_table('grupo_empresa')
    op.drop_table('Unidade')
    op.drop_table('PedidoSOCNET')
    op.drop_table('PedidoProcessamento')
    op.drop_table('Job')
    op.drop_table('Cargo')
    op.drop_table('UsuarioSOC')
    op.drop_table('Usuario')
    op.drop_table('RTCExames')
    op.drop_table('RTCCargos')
    op.drop_table('Prestador')
    op.drop_table('Exame')
    op.drop_table('EmpresaSOCNET')
    op.drop_table('Empresa')
    op.drop_table('TipoUsuario')
    op.drop_table('TipoExame')
    op.drop_table('StatusRAC')
    op.drop_table('StatusLiberacao')
    op.drop_table('Status')
    op.drop_table('RTC')
    op.drop_table('Login')
    op.drop_table('LogAcoes')
    op.drop_table('Grupo')
    op.drop_table('ExportaDadosWS')
    op.drop_table('EmpresaPrincipal')
    op.drop_table('EmailConnect')
    # ### end Alembic commands ###
