"""added client ip table

Revision ID: bb68d52a3f2f
Revises: 41afdc28074b
Create Date: 2023-08-18 16:39:42.523373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb68d52a3f2f'
down_revision = '41afdc28074b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientIP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_addr', sa.String(length=255), nullable=False),
    sa.Column('rate_limit', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_addr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClientIP')
    # ### end Alembic commands ###
