"""added processamento

Revision ID: c646d7d99e94
Revises: edef43398afa
Create Date: 2023-06-28 12:40:47.385715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c646d7d99e94'
down_revision = 'edef43398afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StatusProcessamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TipoProcessamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('erro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['StatusProcessamento.id'], ),
    sa.ForeignKeyConstraint(['tipo'], ['TipoProcessamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Processamento')
    op.drop_table('TipoProcessamento')
    op.drop_table('StatusProcessamento')
    # ### end Alembic commands ###
