"""removed grupo empresa prestador

Revision ID: cc30f7fc236b
Revises: 8d0f575e5df5
Create Date: 2023-10-16 18:51:48.363406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc30f7fc236b'
down_revision = '8d0f575e5df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo_empresa_prestador_socnet')
    op.drop_table('grupo_empresa_prestador')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_empresa_prestador',
    sa.Column('id_grupo', sa.INTEGER(), nullable=True),
    sa.Column('id_empresa', sa.INTEGER(), nullable=True),
    sa.Column('id_prestador', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], )
    )
    op.create_table('grupo_empresa_prestador_socnet',
    sa.Column('id_grupo', sa.INTEGER(), nullable=True),
    sa.Column('id_empresa', sa.INTEGER(), nullable=True),
    sa.Column('id_prestador', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['EmpresaSOCNET.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['Grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_prestador'], ['Prestador.id_prestador'], )
    )
    # ### end Alembic commands ###
