"""updated cod_empresa_referencia relationship

Revision ID: e1741614c9cb
Revises: edef43398afa
Create Date: 2023-06-24 16:22:07.102707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1741614c9cb'
down_revision = 'edef43398afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EmpresaSOCNET', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cod_empresa_referencia', 'EmpresaPrincipal', ['cod_empresa_referencia'], ['cod'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EmpresaSOCNET', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cod_empresa_referencia', type_='foreignkey')
    # ### end Alembic commands ###
