"""added_HistoricoMandatos

Revision ID: edef43398afa
Revises: 023c09953e3c
Create Date: 2023-05-26 21:05:31.698985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edef43398afa'
down_revision = '023c09953e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HistoricoMandatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_mandato', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('cod_empresa_principal', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cod_unidade', sa.String(length=100), nullable=True),
    sa.Column('nome_setor', sa.String(length=255), nullable=True),
    sa.Column('cod_funcionario', sa.Integer(), nullable=False),
    sa.Column('nome_funcionario', sa.String(length=255), nullable=True),
    sa.Column('funcionario_eleito', sa.Boolean(), nullable=True),
    sa.Column('funcionario_renunciou', sa.Boolean(), nullable=True),
    sa.Column('tipo_estabilidade', sa.Integer(), nullable=True),
    sa.Column('descr_estabilidade', sa.String(length=100), nullable=True),
    sa.Column('tipo_representacao', sa.String(length=20), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('tipo_situacao', sa.String(length=10), nullable=True),
    sa.Column('data_inicio_mandato', sa.Date(), nullable=True),
    sa.Column('data_fim_mandato', sa.Date(), nullable=True),
    sa.Column('data_candidatura', sa.Date(), nullable=True),
    sa.Column('data_inicio_eleitoral', sa.Date(), nullable=True),
    sa.Column('data_eleicao', sa.Date(), nullable=True),
    sa.Column('data_inicio_processo', sa.Date(), nullable=True),
    sa.Column('data_inicio_inscricao', sa.Date(), nullable=True),
    sa.Column('data_fim_inscricao', sa.Date(), nullable=True),
    sa.Column('data_prorrogacao', sa.Date(), nullable=True),
    sa.Column('data_estabilidade', sa.Date(), nullable=True),
    sa.Column('data_inclusao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cod_empresa_principal'], ['EmpresaPrincipal.cod'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['Empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hist_mandt_cipa', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('erros_mandt_cipa', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('mandatos_cipa_emails', sa.String(length=500)))

    with op.batch_alter_table('Unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erros_mandt_cipa', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('mandatos_cipa_emails', sa.String(length=500)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HistoricoMandatos')

    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('hist_mandt_cipa')
        batch_op.drop_column('erros_mandt_cipa')
        batch_op.drop_column('mandatos_cipa_emails')

    with op.batch_alter_table('Unidade', schema=None) as batch_op:
        batch_op.drop_column('erros_mandt_cipa')
        batch_op.drop_column('mandatos_cipa_emails')
    # ### end Alembic commands ###
