"""renamed licenca

Revision ID: f02368db0683
Revises: bb68d52a3f2f
Create Date: 2023-08-30 12:28:23.675838

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f02368db0683'
down_revision = 'bb68d52a3f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Licenca', 'Absenteismo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Absenteismo', 'Licenca')
    # ### end Alembic commands ###
